### ISSUE TITLE
Facing Error: qt.qpa.plugin: Could not load the Qt platform plugin "windows" in "" even though it was found. 

### ISSUE THREAD

**Issue by 24Naman** [fding/pyedifice#3]
Hi,
I'm trying to use pyedifice but on running the code, faced with error

> 
> qt.qpa.plugin: Could not load the Qt platform plugin "windows" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: direct2d, minimal, offscreen, windows.
> 
> 

The program used is calculator.py which is provided in the examples directory.

**Solutions Tried**:

_1. Installed pyqt5 (pip install pyqt5)
2. Installed PyQt5-tools (pip install PyQt5-tools)
3. Reinstalled pyedifice_

**Systems detials**:
- OS: Windows 10 (Build: 19042.746)
- Python Version: 3.8.5

Regards

**Comment by fding** [comment]
Hi,

Do you have Pyside2 installed? Otherwise, to use pyqt5, you have to set the EDIFICE_QT_VERSION environment variable to PyQt5, since the default library used is PySide2. You can do this via:
```
EDIFICE_QT_VERSION=PyQt5 python -m edifice calculator.py
```
or
```
export EDIFICE_QT_VERSION=PyQt5  # You can put this in your bashrc or your shell init script
python -m edifice calculator.py
```

Another potential issue with Windows 10 (especially if you want to use the Linux subsystem) is setting up an XServer. Are you able to get raw QT working?
```
from PyQt5 import QtWidgets
app = QtWidgets.QApplication([])
window = QtWidgets.QLabel("Hello World")
window.show()
app.exec_()
```
If not, you might have to install an XServer, e.g. https://sourceforge.net/projects/xming/

Let me know if these solutions work or not!

**Comment by 24Naman** [comment]
Hi,
Setting EDIFICE_QT_VERSION=PyQt5 worked for me.
Thank you very much

**Comment by 0xckylee** [comment]
For Macbook users who have 2 QT libraries crashing together, throwing errors like
"... Export DYLD_PRINT_LIBRARIES=1 and check that only one set of binaries are being loaded.",

`export DYLD_PRINT_LIBRARIES=1
 export EDIFICE_QT_VERSION=PyQt5
`

And remember to put the class name to run at the end
python -m tutorial.py **Oscillator**
